steps:
  - imports:
      align: group
      pad_module_names: true
      long_list_align: multiline
  - language_pragmas:
      align: true
      remove_redundant: false

      # Language prefix to be used for pragma declaration, this allows you to
      # use other options non case-sensitive like "language" or "Language".
      # If a non correct String is provided, it will default to: LANGUAGE.
      language_prefix: LANGUAGE
